// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "demo": datetime Resource Client
//
// Command:
// $ goagen
// --design=github.com/cratermoon/goaelog/design
// --out=$(GOPATH)/src/github.com/cratermoon/goaelog
// --version=v1.2.0-dirty

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// TimeDatetimePath computes a request path to the time action of datetime.
func TimeDatetimePath(tz string, long bool) string {
	param0 := tz
	param1 := strconv.FormatBool(long)

	return fmt.Sprintf("/time/%s/%s", param0, param1)
}

// time returns the time for the timezone (optionally in long format)
func (c *Client) TimeDatetime(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewTimeDatetimeRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewTimeDatetimeRequest create the request corresponding to the time action endpoint of the datetime resource.
func (c *Client) NewTimeDatetimeRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
