// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "demo": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/cratermoon/goaelog/design
// --out=$(GOPATH)/src/github.com/cratermoon/goaelog
// --version=v1.2.0-dirty

package client
