// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "demo": uuid Resource Client
//
// Command:
// $ goagen
// --design=github.com/cratermoon/goaelog/design
// --out=$(GOPATH)/src/github.com/cratermoon/goaelog
// --version=v1.2.0-dirty

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GenerateUUIDPath computes a request path to the generate action of uuid.
func GenerateUUIDPath() string {

	return fmt.Sprintf("/uuid")
}

// generate returns a new randomly generated uuid
func (c *Client) GenerateUUID(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewGenerateUUIDRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGenerateUUIDRequest create the request corresponding to the generate action endpoint of the uuid resource.
func (c *Client) NewGenerateUUIDRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
